__title__ = "myqiwi"
__description__ = "Python qiwi api for Humans."
__url__ = "https://github.com/daveusa31/myqiwi"
__version__ = "0.1"
__author__ = "daveusa"
__author_email__ = "daveusa@yandex.ru"
__license__ = "MIT"
